### ISSUE TITLE
Not Compatible for UVM testbench?

### ISSUE THREAD

**Issue by AbdullahHassaanAhmad** [catkira/open5G_phy#33]
Hi,

Seeing that tests are being run for this IP using python files, where supposedly the input metadeta is taken from some '.sigmf-data' files present in the tests directory, but for UVM testbench, IQ samples need to be assigned directly in the uvm_sequence and every signal is driven individually without taking input from any files, it seems to not work for that, because giving any input on signals like 's_axis_in_tdata', 's_axis_in_I_tdata', and 's_axis_in_Q_tdata' makes nothing appear on uvm_monitor. Do verifiying using UVM, compatible for this IP or is this a bug?

**Comment by catkira** [comment]
what is a UVM testbench?

**Comment by AbdullahHassaanAhmad** [comment]
Universal Verification Methodology Testbench

**Comment by catkira** [comment]
I don't use this methodology.

**Comment by AbdullahHassaanAhmad** [comment]
Okay, Thanks
